<?php

namespace AppBundle\Repository;

/**
 * RSSFeedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RSSFeedRepository extends \Doctrine\ORM\EntityRepository
{
}
